apiVersion: apps/v1
kind: Deployment
metadata:
  name: cannafacts-twitch
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cannafacts-twitch
  template:
    metadata:
      labels:
        app: cannafacts-twitch
    spec:
      containers:
      - name: cannafacts-twitch 
        image: "devopswithbrian/cannafacts-twitch:0.4.0"
        imagePullPolicy: Always
        tty: true
        env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: cannafacts-twitch-prd
                key: TOKEN
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: cannafacts-twitch-prd
                key: CLIENT_ID
          - name: CHANNEL
            valueFrom:
              secretKeyRef:
                name: cannafacts-twitch-prd
                key: CHANNEL
          - name: BOT_PREFIX
            valueFrom:
              secretKeyRef:
                name: cannafacts-twitch-prd
                key: BOT_PREFIX
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: cannafacts-twitch-prd
                key: API_URL